### ISSUE TITLE
Support Nix channels

### ISSUE THREAD

**Issue by andir** [andir/npins#18]
We should support nix channels. Those are/were the actual official way to distribute revisions of a channel.

It esentially boils down to:

```shell
$ curl -s -i https://nixos.org/channels/nixos-21.11 -L | grep -i '^location:' 
location: https://channels.nixos.org/nixos-21.11
location: https://releases.nixos.org/nixos/21.11/nixos-21.11.335037.e67c94a1adb
```

We should then prefetch the file `https://releases.nixos.org/nixos/21.11/nixos-21.11.335037.e67c94a1adb/nixexprs.tar.xz`.

**Comment by piegamesde** [comment]
I'd be willing to give it a shot after the current PR backlog has been processed (there are too many pending refactorings that will guarantee merge conflicts right now).
