### ISSUE TITLE
Documentation providing guidance on how to use `npins` to manage a NixOS configuration? 

### ISSUE THREAD

**Issue by bzm3r** [andir/npins#53]
From what I have been able to piece together so far in order to figure out how to use `npins` to manage a NixOS configuration (flake-less):

1) Inside configuration.nix, it is necessary to overlay the `nixpkgs` pinned by `npins`:

```nix
{ config, ... }:
{
  nixpkgs.overlays = 
    let 
      npinsOverlay = self: _super: {
        inherit (sources) nixpkgs;
      };
    in
      [ npinsOverlay ];
}
```

2) Easily building with `nixos-rebuild` requires further steps still ([adapted from a solution for `niv`](https://discourse.nixos.org/t/pinning-nixpkgs-in-configuration-nix-using-niv/12607/8)), namely the creation of a `shell.nix` (possibly using the help of `direnv` to automatically switch into this shell when entering the the NixOS configuration  directory).

The `shell.nix` probably looks like this:
```nix
let
  sources = import ./npins;
  pkgs = import sources.nixpkgs {};
in
pkgs.mkShell {
        buildInputs = with pkgs; [
                npins
                # what else should go here?
        ];
        shellHook = ''
                export nixpkgs=${sources.nixpkgs.outPath}
                export NIX_PATH=nixpkgs=${sources.nixpkgs.outPath}:nixos-config=/path/to/your/nixos-config/configuration.nix
        '';
}
```

I am not sure what other packages ought to be/are useful to include in `buildInputs`

3) Building a custom live ISO will also need to happen inside this shell.  

Am I missing anything else? I'd appreciate some feedback, and if there is interest, would be happy to help submit a PR which adds a small section documenting the above within `README`.

**Comment by piegamesde** [comment]
Your overlay looks weird. Why aren't you simply overriding the nixpkgs entirely?

Also in your `shell.nix`, you probably want to remove the function arguments and put them into a let binding instead.

Generally, I recommend using a build tool like colmena or morph to manage the NixOS configuration, as you then don't need to manually call the rebuild commands in a shell anymore. Many of these tools also support deploying to the local machine.
