### ISSUE TITLE
How to add an entry with name `nixpkgs` tracking a specific `nixpkgs-*` channel?

### ISSUE THREAD

**Issue by bzm3r** [andir/npins#54]
Running `npins init` creates a `nixpkgs` based on unstable.

Suppose I run `npins remove nixpkgs`. What `npins add` based command can I run to re-insert a source named `nixpkgs` based on (for the sake of example) the `nixpkgs-unstable` channel?

**Comment by piegamesde** [comment]
`npins add --name nixpkgs channel nixpkgs-unstable`
