### ISSUE TITLE
Is adding a `nixos` source a common usage action?

### ISSUE THREAD

**Issue by bzm3r** [andir/npins#55]
Under [Adding Dependencies](https://github.com/andir/npins#adding-dependencies) the README gives as an example:

```
npins add channel nixos-21.11
```

But under what situations would one to add `nixos-*`? NixOS tests?

After all, `nixos-*` doesn't contain `nixpkgs-*` (which is what is required to set up NixOS)? 

So is this actually good example for this section, or would it be better to have 

```
npins add channel nixpkgs-21.11
```

**Comment by piegamesde** [comment]
NixOS modules are part of Nixpkgs, and thus the nixos channels contain all you need. The only difference is in the test set which gets run on them. https://nixos.wiki/wiki/Nix_channels
