### ISSUE TITLE
How to update a pin's channel?

### ISSUE THREAD

**Issue by bzm3r** [andir/npins#56]
Suppose I run `npins init --bar`, and then `npins add channel nixpkgs-stable`. 

Assume I take the the trouble to rename `nixpkgs-23.05` to `stable` in `source.json`. 

Now, in the future, suppose I want to switch to `nixpkgs-23.11`. Is there any way for me to do that using `npins`? (I think not?) Essentially an equivalent for the following from `niv`: 

```
niv update nixpkgs --branch nixos-23.11
```

**Comment by piegamesde** [comment]
Simply re-adding with `npins add --name nixpkgs channel nixos-23.11` should work.

**Comment by bzm3r** [comment]
@piegamesde Aha! Thanks! I was misunderstanding what the `name` option was for. I think it would be helpful if it did have a small string describing what its purpose is.
